#!/usr/bin/perl

################################################################################
#
# Change the foreground and background colors on the fly.
#
# Copyright (c) 2015-2017, Peter J. Jones <pjones@devalot.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the
#    distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


use strict;
use warnings;

sub on_start
{
    my ($self) = @_;
    $self->{"origBackground"} = $self->x_resource("background");
    $self->{"origForeground"} = $self->x_resource("foreground");
    $self->{"altBackground"}  = $self->x_resource("altBackground");
    $self->{"altForeground"}  = $self->x_resource("altForeground");
    $self->{"curBackground"}  = $self->{"origBackground"};
}

sub on_user_command
{
    my ($self, $cmd) = @_;

    if ($cmd eq "colors:toggle") {
        $self->toggle_colors;
    }
}

sub toggle_colors
{
    my ($self) = @_;

    if ($self->{"curBackground"} eq $self->{"origBackground"}) {
        $self->set_colors("alt");
    } else {
        $self->set_colors("orig");
    }
}

sub set_colors
{
    my ($self, $prefix) = @_;
    my $foreground = $self->{$prefix . "Foreground"};
    my $background = $self->{$prefix . "Background"};

    $self->{"curBackground"} = $background;
    $self->cmd_parse("\033]10;" . $foreground . "\033\\");
    $self->cmd_parse("\033]11;" . $background . "\033\\");
}
